# Generated by Django 3.1 on 2020-09-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('position', models.TextField(max_length=50, null=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Balloon blowing', 'Balloon blowing'), ('Swaging', 'Swaging'), ('Proximal welding', 'Proximal welding'), ('Pleating', 'Pleating')], max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.engineer')),
            ],
        ),
    ]
