# Generated by Django 3.1 on 2020-10-01 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20200930_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
