# Generated by Django 3.1 on 2020-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_auto_20201004_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='profile_pic',
            field=models.ImageField(default='images/profile.png', upload_to=''),
        ),
    ]
