# Generated by Django 3.1 on 2020-10-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_auto_20201024_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='follower_id',
            field=models.ManyToManyField(blank=True, related_name='follower', to='task_app.Engineer'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='following_id',
            field=models.ManyToManyField(blank=True, related_name='following', to='task_app.Engineer'),
        ),
    ]
