# Generated by Django 3.1 on 2020-10-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0013_auto_20201028_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='follower_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='task_app.engineer'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='task_app.engineer'),
        ),
    ]
