# Generated by Django 3.1 on 2020-10-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0015_auto_20201028_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='following',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_owner', to='task_app.engineer'),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='task_app.engineer')),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_owner', to='task_app.engineer')),
            ],
        ),
    ]
